name: GH and Hex.pm Release

on:
  push:
    tags:
      - v*.*.*
jobs:
  release:
    uses: TanklesXL/gleam_actions/.github/workflows/release.yaml@main
    secrets: inherit
    with:
      gleam_version: 1.9.1
      erlang_version: 26
      test_erlang: true
      test_node: false
